# Generated by Django 4.2.7 on 2023-11-07 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Melody', 'Melody'), ('Workout', 'Workout'), ('Travel', 'Travel'), ('Night Times', 'Night Times')], default='Pop', max_length=50)),
                ('composer', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('audio_file', models.FileField(upload_to='songs/')),
            ],
            options={
                'permissions': (('can_add_song', 'Can add song'), ('can_edit_song', 'Can edit song'), ('can_delete_song', 'Can delete song')),
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Melody', 'Melody'), ('Workout', 'Workout'), ('Travel', 'Travel'), ('Night Times', 'Night Times')], default='Pop', max_length=100)),
                ('playlist_image', models.ImageField(upload_to='images/')),
                ('songs', models.ManyToManyField(to='main_app.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
