# Generated by Django 4.2.7 on 2023-11-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('jazz', 'Jazz'), ('melody', 'Melody'), ('workout', 'Workout'), ('travel', 'Travel'), ('night_times', 'Night Times')], default='pop', max_length=100)),
            ],
        ),
    ]
