# Generated by Django 4.2.7 on 2023-11-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Melody', 'Melody'), ('Workout', 'Workout'), ('Travel', 'Travel'), ('Night Times', 'Night Times')], default='Pop', max_length=100)),
                ('released_year', models.PositiveIntegerField(blank=True, default={'max_value': 2099, 'min_value': 1900}, help_text='The year in which it was released.', null=True, verbose_name='Released Year')),
            ],
        ),
        migrations.AlterField(
            model_name='playlist',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Melody', 'Melody'), ('Workout', 'Workout'), ('Travel', 'Travel'), ('Night Times', 'Night Times')], default='Pop', max_length=100),
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='main_app.song'),
        ),
    ]
