# Generated by Django 4.2.7 on 2023-11-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_song_alter_playlist_genre_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='null', upload_to='songs/'),
            preserve_default=False,
        ),
    ]
